# version: '28.1.1'            ## writing version numbers is obsolete now 
services:
  app:
    build: ./app
    ports:
      - 5000:5000
  db:
    image: mysql:9.4
    ports:
      - 32000:3306
    environment:
      - MYSQL_ROOT_PASSWORD=12345
    volumes:
      - ./db:/docker-entrypoint-initdb.d/